spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reconx_uat
    username: reconx_uat
    password: reconx_uat
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 5000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.batch_size: 50

logging:
  level:
    com.dbtraining.reconx: INFO
